### ISSUE TITLE
Make include guards unique.

### ISSUE THREAD

**Issue by elfring** [infinisql/infinisql#11]
I find that include guards like "[API_H](https://github.com/infinisql/infinisql/blob/b928ac619e71fbdd3162d4c104f10389c39ce381/infinisqld/infinisql_api.h#L27)" and "[TABLE_HPP](https://github.com/infinisql/infinisql/blob/ef629595ff878a362a0c2150177fa3f95100e8e7/infinisqld/infinisql_Table.h#L26)" are too short for the safe reuse of your header files.

**Comment by mtravis15432** [comment]
Thanks, elfring. I'll keep this open and make sure to include your suggestion in the next push.

And thank you for going through the code. My main objective in the very near term is documentation such that Doxygen can give a complete picture, as far as possible. That will be the next push that I make to HEAD, that will be included with the new header guards.

**Comment by mtravis15432** [comment]
I've committed this, it will show up in the next push.
