### ISSUE TITLE
ORM Conformance Testing

### ISSUE THREAD

**Issue by techdragon** [infinisql/infinisql#30]
Can we get some kind of conformance testing against SQL using software like the Django ORM, MediaWiki, Wordpress, Rails Active Record, etc. 

Conformance testing would help show people that they can actually **use** this software even if that use comes with some risk due to its level of maturity. Right now I have no way of knowing if InfiniSQL works with anything other than my own brand new hand written SQL statements.

**Comment by cleder** [comment]
Is there a detailed how to how to get data from postgresql (or another
rdbms) into infisql?
PostgresQl would be the preferred way as it would only entail export/import
and change the port from postgresql ti infinisql

On Mon, Jun 2, 2014 at 9:58 AM, Samuel Bishop notifications@github.com
wrote:

> Can we get some kind of conformance testing against SQL using software
> like the Django ORM, MediaWiki, Wordpress, Rails Active Record, etc.
> 
> Conformance testing would help show people that they can actually _use_
> this software even if that use comes with some risk due to its level of
> maturity. Right now I have no way of knowing if InfiniSQL works with
> anything other than my own brand new hand written SQL statements.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/infinisql/infinisql/issues/30.

## 

Best Regards,

Christian Ledermann

London - UK
Mobile : +44 7899488511

<*)))>{

If you save the living environment, the biodiversity that we have left,
you will also automatically save the physical environment, too. But If
you only save the physical environment, you will ultimately lose both.

1) Don’t drive species to extinction

2) Don’t destroy a habitat that species rely on.

3) Don’t change the climate in ways that will result in the above.

}<(((*>
